### PR TITLE
Click 7 support

### LINKED ISSUE #2: Broken with click 7
https://travis-ci.org/jayvdb/click-aliases/jobs/568251511
```
runner = <click.testing.CliRunner object at 0x7fb65f97a550>
    def test_cli(runner):
        result = runner.invoke(cli)
>       assert result.output == TEST_CLI
E       AssertionError: assert 'Usage: cli [... ship (boat)\n' == 'Usage: cli [O...ages ships.\n'
E         Skipping 116 identical leading characters in diff, use -v to show
E         - ine (bomb)
E         -   ship (boat)
E         + ine (bomb)  Manages mines.
E         +   ship (boat)  Manages ships.
tests/test_naval.py:88: AssertionError

________________________________ test_ship_help ________________________________
runner = <click.testing.CliRunner object at 0x7fb65f97b110>

    def test_ship_help(runner):
        for cmd in ['ship', 'boat']:
            result = runner.invoke(cli, [cmd])
>           assert result.output == TEST_SHIP_HELP.format(cmd=cmd)
E           AssertionError: assert 'Usage: cli s...shoot (fire)\n' == 'Usage: cli sh...ire to X,Y.\n'
E             Skipping 134 identical leading characters in diff, use -v to show
E             - ,navigate)
E             -   new (add,build,create)
E             -   shoot (fire)
E             + ,navigate)   Moves SHIP to the new location X,Y.
E             +   new (add,build,create)  Creates a new ship.
E             +   shoot (fire)            Makes SHIP fire to X,Y.
```

### PR DESCRIPTION
**Pull request by jayvdb**
Closes #2

### CODE REVIEW

**Comment by jayvdb** [comment]
ping @rbonthond , could you take a look at this

**Comment by jayvdb** [comment]
Perhaps @timofurrer, do you have the ability to help with this?

There are real users of it.  c.f. [github code search](https://github.com/search?q=click-aliases&type=Code)

I'd like to get this packaged for openSUSE, which uses Python 3.7, and I have a ["large" collection](https://software.opensuse.org/search?utf8=%E2%9C%93&baseproject=ALL&q=click-) of click plugins.

**Comment by timofurrer** [comment]
I've just realized, that I don't have the permissions to merge this. 
@click-contrib/maintainers Can someone of you help out here? Or grant me the commit bit here? 
I'm already maintaining some repos in this org ..

**Comment by untitaker** [comment]
@timofurrer not all org members have access to all repos. Please ask @rbonthond if it's ok, then I will grant you acess

**Comment by timofurrer** [comment]
Yeah, sure. I've emailed @rbonthond ... Let's see.

**Comment by rbonthond** [comment]
Sorry, these pull requests got lost in spam, I've merged it now, and will see how I can add more maintainers to this repository

**Comment by rbonthond** [comment]
@unitaker feel free to add @timofurer

**Comment by untitaker** [comment]
done!

**Pull request merged**
